import {
  slide1,
  slide2,
  slide3,
  slide4,
  slide5,
  slide6,
  slide7,
  slide8,
  slide9,
  slide10,
  slide11,
  slide12,
  slide13,
  slide14,
} from "../../assets/images";

export const SliderData = [
  { src: slide1, url: "https://www.brandi.co.kr/event/28471" },
  { src: slide2, url: "https://www.brandi.co.kr/event/31750" },
  { src: slide3, url: "https://www.brandi.co.kr/event/31771" },
  { src: slide4, url: "https://www.brandi.co.kr/event/31749" },
  { src: slide5, url: "https://www.brandi.co.kr/event/31744" },
  { src: slide6, url: "https://www.brandi.co.kr/event/31751" },
  { src: slide7, url: "https://www.brandi.co.kr/event/31746" },
  { src: slide8, url: "https://www.brandi.co.kr/event/31747" },
  { src: slide9, url: "https://www.brandi.co.kr/event/31726" },
  { src: slide10, url: "https://www.brandi.co.kr/event/31755" },
  { src: slide11, url: "https://www.brandi.co.kr/event/31725" },
  { src: slide12, url: "https://www.brandi.co.kr/event/31753" },
  { src: slide13, url: "https://www.brandi.co.kr/event/31745" },
  { src: slide14, url: "https://www.brandi.co.kr/event/31752" },
];
